Revert "[ios][feed] Add reset flag for First Follow count"
This reverts commit c6820f2656dd6c3c6235a46781b471fded9bf63c.

Reason for revert: The caller side haven't been changed, so it fails the ToT with error:

../../ios_internal/chrome/browser/providers/discover_feed/internal_discover_feed_service.mm:166:27: error: no member named 'ShouldResetNoticeCardOnFeedStart' in namespace 'experimental_flags'
  if (experimental_flags::ShouldResetNoticeCardOnFeedStart()) {

Original change's description:
> [ios][feed] Add reset flag for First Follow count
>
> Reset flag allows for easier testing.
>
> Bug: 1312124
> Change-Id: Ic5d9953b9917fc5f58410bb6f92412bce7b75d8a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3564107
> Reviewed-by: Sergio Collazos <sczs@chromium.org>
> Reviewed-by: Tina Wang <tinazwang@chromium.org>
> Commit-Queue: edchin <edchin@google.com>
> Reviewed-by: Adam Arcaro <adamta@google.com>
> Cr-Commit-Position: refs/heads/main@{#988037}

Bug: 1312124
Change-Id: I44a9370605b2f9bce3813d150b3dc51de7f1e491
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3565644
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: edchin <edchin@google.com>
Reviewed-by: Rohit Rao <rohitrao@chromium.org>
Commit-Queue: edchin <edchin@google.com>
Cr-Commit-Position: refs/heads/main@{#988085}
NOKEYCHECK=True
GitOrigin-RevId: 74e08aa0833b207f3756d88956acc34088662763