Revert "[iOS][media-permissions] Expose API to WebStateDelegateBridge"
This reverts commit 38fd4657f1f4c6f1dd7bf4aba7688d13c29bbf80.

Reason for revert:

Breaks ios-web-view-simulator bot. See error below.
https://ci.chromium.org/ui/p/chrome/builders/ci/ios-web-view-simulator/38351/overview

[556/708] OBJCXX obj/ios/web/ios_web_web_state_unittests/web_state_delegate_bridge_unittest.o
FAILED: obj/ios/web/ios_web_web_state_unittests/web_state_delegate_bridge_unittest.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../ios/web/web_state/web_state_delegate_bridge_unittest.mm:144:37: error: 'HandlePermissionsDecisionRequest' is only available on iOS 15.0 or newer [-Werror,-Wunguarded-availability-new]
bool useHandlerAnswerTheRequest = bridge_->HandlePermissionsDecisionRequest(
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Original change's description:
> [iOS][media-permissions] Expose API to WebStateDelegateBridge
>
> This CL exposes the API for handling media permissions to
> WebStateDelegateBridge to make it available for use by //ios/web/shell
> and //ios/web_view.
>
> Change-Id: I7f8f30feceab0ebe5a2c122a01a1c24d7f838633
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4402281
> Reviewed-by: Gauthier Ambard <gambard@chromium.org>
> Commit-Queue: Zengfeng Ye <zenye@microsoft.com>
> Reviewed-by: Ali Juma <ajuma@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1127517}

Change-Id: I3ee05ec8574f322d7a2b69607a0168e11fdddf47
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4409390
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: edchin <edchin@google.com>
Commit-Queue: edchin <edchin@google.com>
Reviewed-by: edchin <edchin@google.com>
Owners-Override: edchin <edchin@google.com>
Cr-Commit-Position: refs/heads/main@{#1127718}
NOKEYCHECK=True
GitOrigin-RevId: d24633099d99153423012dc40a185effde2ad054