[ios] Fix broken build
Cause:
features.mm:57:8: error: code will never be executed

Bug: 1348103
Change-Id: I81218e26420d315b492ab7624fcdf3ebe512d73d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3789686
Quick-Run: David Jean <djean@chromium.org>
Owners-Override: David Jean <djean@chromium.org>
Commit-Queue: edchin <edchin@google.com>
Reviewed-by: Olivier Robin <olivierrobin@chromium.org>
Reviewed-by: edchin <edchin@google.com>
Auto-Submit: David Jean <djean@chromium.org>
Reviewed-by: Gauthier Ambard <gambard@chromium.org>
Commit-Queue: Gauthier Ambard <gambard@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1029137}
NOKEYCHECK=True
GitOrigin-RevId: f987747dd8a74930b551a2bbba538bd5760112da